- name: Install htop
  hosts: all
  become: yes
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install htop
      apt:
        name: htop
        state: present
        update_cache: yes
